//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CarSoldData
    {
        public string Customer_Name { get; set; }
        public string SerialNumber { get; set; }
        public string Supplier_Name { get; set; }
        public decimal Agreed_Price { get; set; }
        public System.DateTime Date_Sold { get; set; }
    }
}
