//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCarLoan
    {
        public int Loan_ID { get; set; }
        public Nullable<int> CarSold_ID { get; set; }
        public Nullable<int> FinanceCompany_ID { get; set; }
        public System.DateTime RepaymentStartDate { get; set; }
        public System.DateTime RepaymentEndDate { get; set; }
        public decimal MonthlyRepayments { get; set; }
    
        public virtual tblCarsSold tblCarsSold { get; set; }
        public virtual tblFinanceCompany tblFinanceCompany { get; set; }
    }
}
