//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCustomerPayment
    {
        public int CustomerPayments_ID { get; set; }
        public Nullable<int> CarSold_ID { get; set; }
        public Nullable<int> Customer_ID { get; set; }
        public Nullable<int> PaymentStatus_CODE { get; set; }
        public System.DateTime CustomerPaymentDateDue { get; set; }
        public decimal ActualPaymentAmount { get; set; }
    
        public virtual tblCarsSold tblCarsSold { get; set; }
        public virtual tblCustomer tblCustomer { get; set; }
        public virtual tblPaymentStatu tblPaymentStatu { get; set; }
    }
}
